from abc import ABC, abstractmethod


class ProductoBancario(ABC):
    @abstractmethod
    def depositar(self, monto: float) -> None: ...
    @abstractmethod
    def retirar(self, monto: float) -> None: ...
    @abstractmethod
    def calcular_intereses(self) -> float: ...
    @abstractmethod
    def pagar_cuota(self, monto: float) -> None: ...
    @abstractmethod
    def generar_extracto(self) -> str: ...
